apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: bankapp
  name: {{.Values.application.name}}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: bankapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bankapp
    spec:
      containers:
      - image: {{.Values.image.repository}}
        name: bankapp
        imagePullPolicy: {{.Values.image.pullPolicy}}
        resources: {}
        ports:
          - containerPort: 80 
status: {}
